python.24 = $(HOME)/venv/py24
python.25 = $(HOME)/venv/py25
python.26 = $(HOME)/venv/py26
python.27 = $(HOME)/venv/py27
python.34 = $(HOME)/venv/py34
python.35 = $(HOME)/venv/py35
python.36 = $(HOME)/venv/py36
python.37 = $(HOME)/venv/py37
python.38 = $(HOME)/venv/py38
python.39 = $(HOME)/venv/py39

.uri =

python-home := $(python.$(if $(python),$(python),$($(db).python)))
python-bin = $(python-home)/bin
export PATH := $(python-bin)$:$(PATH)

pip-freeze:
	pip freeze -l
