python.24-0.12 = $(HOME)/venv/py24-0.12
python.25-0.12 = $(HOME)/venv/py25-0.12
python.26-0.12 = $(HOME)/venv/py26-0.12
python.27-0.12 = $(HOME)/venv/py27-0.12
python.25-1.0  = $(HOME)/venv/py25-1.0
python.26-1.0  = $(HOME)/venv/py26-1.0
python.27-1.0  = $(HOME)/venv/py27-1.0
python.25-1.1  = $(HOME)/venv/py25-1.1
python.26-1.1  = $(HOME)/venv/py26-1.1
python.27-1.1  = $(HOME)/venv/py27-1.1
python.26-1.2  = $(HOME)/venv/py26-1.1
python.27-1.2  = $(HOME)/venv/py27-1.1

.uri =

python-home := $(python.$(if $(python),$(python),$($(db).python)))
python-bin = $(python-home)/bin
export PATH := $(python-bin)$:$(PATH)

pip-freeze:
	pip freeze -l
